### PR TITLE
Fix link generation for simple outline rendering

### LINKED ISSUE #11: Links in left side outline are incorrectly transformed to remove surrounding _ _
Building with:

`lang ❯ typedoc --theme /Users/crucialfelix/.nvm/versions/node/v10.15.1/lib/node_modules/typedoc-neo-theme/bin/default`

(globally installed neo-theme)

creates a front page:
`file:///Users/crucialfelix/code/supercolliderjs/docs/packages/lang/docs/index.html`

The generated source contains items in `.tsd-navigation-primary` that populate the sidebar:

```
<li class=" tsd-kind-external-module">
  <a href="modules/_sclang_.html" style="display:none">sclang</a>
</li>
```

These links are correct (but invisible). Each module is surrounded with `_`modulename`_`.html

But this is then rendered to the DOM (by frontend javascript AFAICT) as:

`<a href="modules/sclang.html">sclang</a>`

ie:
`file:///Users/crucialfelix/code/supercolliderjs/docs/packages/lang/docs/modules/sclang.html`

*Without* the surrounding underscores.  Which is 404

### LINKED ISSUE #16: Navigation link error after using theme
After a closer look, the initial HTML returned was correct

Before use

If you don't use `typedoc-neo-theme`, the link is normal. It seems that` typedoc-neo-theme` does something. . .
image

---

After use

After a closer look, the initial HTML returned was correct
image

But it changed after `main.js` was run, and I don't know what happened. . .
image
image

I have communicated under typedoc before, but it feels like it should be a topic issue. . .

> Reference: <https://github.com/TypeStrong/typedoc/issues/1147>

### PR DESCRIPTION
**Pull request by Fleker**
Fixes #11
Fixes #16

Change-Id: Id134fbe04ba5941a67be308cf5015da0e4d6804b

### CODE REVIEW

**Comment by Fleker** [comment]
Here's how it will look without a custom outline:

image

**Comment by Fleker** [comment]
`main.js` is auto-generated, and it seems to be using concatenation as part of the generation process.

**Comment by rxliuli** [comment]
Problems still <https://github.com/google/typedoc-neo-theme/issues/11#issuecomment-568153660>, I tried to fix <https://github.com/google/typedoc-neo-theme/pull/21>

**Comment by Fleker** [comment]
Fixed actually in #21

**Pull request closed without merging**
