### PR TITLE
Update globals -> modules for typedoc 0.20.*

### LINKED ISSUE #67: Theme references `globals.html` which TypeDoc 0.20 does not emit
TypeDoc v0.20 now emits a file `modules.html`, which the default themes style as "Exports" instead of "Globals".

When specifying `outline` in typedoc.json, this theme hardcodes "Globals" in the outline, resulting in a broken href. This is hardcoded in the [default layout](https://github.com/google/typedoc-neo-theme/blob/master/third_party/src/default/layouts/default.hbs#L31).

This theme should respect the new TypeDoc behavior and not generate links to files that don't exist.

### PR DESCRIPTION
**Pull request by mehtaphysical**
Fixes #67.

Small change. Not sure about the test and all that.

### CODE REVIEW

**Comment by Fleker** [comment]
Thanks for making this PR. You will need to sign the CLA before this can be accepted.

Cloud Build is throwing an exception on `Search.ts` lint, which isn't related to this. But updating the sample doc and making sure that test passes is going to be valuable so that we can verify what changes the output has.

**Comment by Fleker** [comment]
This is now fixed in 305ce9d6d8f08a00a1ea9131750a20c0166b6a5e

**Comment by mehtaphysical** [comment]
Thanks! What's the release schedule for this?

**Comment by Fleker** [comment]
I also need to patch search again, so once that's fixed I'll bundle both changes in a new release.

**Pull request closed without merging**
